### ISSUE TITLE
EOS Staked issue. None Prof

### ISSUE THREAD

**Issue by abusaad11** [abhi3700/My_Learning_EOS#3]
i cant get my EOS out. im not sure what i did before some years,. now i got this SC

![image](https://user-images.githubusercontent.com/36753899/120246696-12178380-c282-11eb-8b98-22bd67abc234.png)

any help pls

bitcoin17489@outlook.com

Hezdgmjxguge

**Comment by abhi3700** [comment]
@abusaad11 
It's not a smart contract. Doesn't have any table or code inside.
<img width="954" alt="image" src="https://user-images.githubusercontent.com/16472948/196054747-fda7b07e-f9f7-46ed-87a0-ea59b90635b5.png">
